# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    tags: [ "*" ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_configuration: [Release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{ matrix.build_configuration }} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload executable
      if: matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: NalFix
        path: NalFix\bin\Release\NalFix.exe

    - name: Upload executable to release
      if: startsWith(github.ref, 'refs/tags/') && matrix.build_configuration == 'Release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: NalFix\bin\Release\NalFix.exe
        asset_name: NalFix.exe
        tag: ${{ github.ref }}
        overwrite: true
